%Import Actigraph IMU rawfile (accelerometer and gyroscope)

function IMUrawdata = importIMUfile(filename, startRow, endRow)
%   IMUrawdata = importIMUfile(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   IMUrawdata = importIMUfile(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   Trial1AlannahWaistNew20150219IMU = importfile1('Trial 1 Alannah Waist
%   New (2015-02-19)-IMU.csv', 12, 70311);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/03/10 17:37:01

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 12;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%*s%f%f%f%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([2, 3, 4, 5, 6, 7]) = cellfun(@(x) num2cell(x), dataArray([2, 3, 4, 5, 6, 7]), 'UniformOutput', false);
IMUrawdata = [dataArray{1:end-1}];
